version: '3'

networks:
  default:
    external:
      name: localdev

services:
  nexus:
    container_name: nexus_migration
    image: sonatype/nexus3:3.38.1
    ports:
      - "0.0.0.0:32333:8081"
      - "0.0.0.0:32334:5000"
      - "0.0.0.0:32335:8081"
      - "0.0.0.0:32336:8082"
      - "0.0.0.0:32337:8083"
      - "0.0.0.0:32338:8084"
      - "0.0.0.0:32339:8085"
      - "0.0.0.0:32340:8092"
      - "0.0.0.0:32341:8093"
  
    volumes:
      - /grid/0/nexus:/nexus-data:rw
    extra_hosts:
      - "sgproxy.kyivstar.ua:10.49.72.30"
    # environment:
    #   PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    #   container: oci,
    #   SONATYPE_DIR: /opt/sonatype,
    #   NEXUS_HOME: /opt/sonatype/nexus,
    #   NEXUS_DATA: /nexus-data,
    #   SONATYPE_WORK: /opt/sonatype/sonatype-work,
    #   DOCKER_TYPE: rh-docker,
    #   INSTALL4J_ADD_VM_PARAMS: -Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    # command: ["-c", "${SONATYPE_DIR}/start-nexus-repository-manager.sh"]
