version: '3.3'

networks:
  default:
    external:
      name: localdev

services:
  prometheus:
    image: pmdoubez/filestat_exporter
    container_name: nifi_monitoring_exporter
    user: "1000:1000"
    volumes:
      - /data:/SrcFiles/nifi_monitoring:ro
      - /grid/0/prometheus/filestat/filestat.yaml:/filestat.yaml

    command:
      - '-config.file=/filestat.yaml'
    ports:
      - 0.0.0.0:9943:9943
    environment:
      - no_proxy=127.0.0.0/8,10.0.0.0/8,*.example.com
      - http_proxy=http://sgproxy.example.com:3128
      - https_proxy=http://sgproxy.example.com:3128
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    restart: always