exporter:
  # Optional network parameters
  listen_address: ':9943'
  #metrics_path: /metrics
  
  # Optional working directory - overridden by parameter '-path.cwd'
  working_directory: "/data"
  # Default enable/disable of metrics - overridden if not set by parameter '-metric.*'
  enable_crc32_metric: true
  # enable_nb_line_metric: false
  # list of patterns to apply - metrics can be enable/disabled for each group
  files:
    - patterns: ["ks-*"]
    # - patterns: ["data/*.csv"]
      enable_nb_line_metric: true
    # - patterns: ["archives/*.tar.gz"]
    #   enable_crc32_metric: false
    #   enable_nb_line_metric: false