version: '3.3'

networks:
  default:
    external:
      name: localdev

services:
  prometheus-alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: prometheus-alertmanager
    volumes:
      - /opt/alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      # - '--web.external-url=http://ks-dmp45.kyivstar.ua:9090/'
    ports:
      - 0.0.0.0:9093:9093
    # environment:
    #   - no_proxy=127.0.0.0/8,10.0.0.0/8,*.kyivstar.ua
    #   - http_proxy=http://sgproxy.kyivstar.ua:3128
    #   - https_proxy=http://sgproxy.kyivstar.ua:3128
    #   - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    restart: always