version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:10-3.0
    ports:
      - 0.0.0.0:5432:5432   
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:9.0.0-rc.90
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - /directus/uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'
      #DB_EXCLUDE_TABLES: 'spatial_ref_sys,sysdiagrams,temp_services_contract,temp_short_numbers,old_api_clients_scoring_config,old_amount_ranges,old_billing_callback_numbers,old_streams,old_short_numbers,old_services_managers,old_services_contract,old_services,old_managers,old_forecasts,old_forecast_types,old_contracts,old_conditions_services_old,old_clients,old_categories,dwh_r_018936_nbs_main_r,billing_callback_numbers_okpo_mapping_r,bds_companies_r,bds_billing_mapping_r'
      DB_EXCLUDE_TABLES: 'dpi_taxon_segment_latest,dim_city_poly,ds_adtech_client_old,ds_adtech_profile_map_old,temp_short_numbers,ds_adtech_segment_old,temp_services_contract'
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

      # Make sure to set this in production
      # (see https://docs.directus.io/configuration/config-options/#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus: