version: '3.3'

networks:
  default:
    external:
      name: localdev

services:
  prometheus:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: prometheus-postgres-exporter
    ports:
      - 0.0.0.0:9187:9087
    environment:
      - no_proxy=127.0.0.0/8,10.0.0.0/8,*.kyivstar.ua
      - http_proxy=http://sgproxy.kyivstar.ua:3128
      - https_proxy=http://sgproxy.kyivstar.ua:3128
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - DATA_SOURCE_NAME="postgresql://prometheus:passwd@host:port/database?sslmode=disable"
    restart: always
