version: "3.7"
services:
    wso2test:
        image: wso2/wso2am:2.6.0-centos
        networks:
          - wso2test
        labels:
          com.example.description: "Test WSO2AM API"
        domainname: kyivstar.ua
        hostname: ks-dmp-dev03
        extra_hosts:
         - "ks-dmp-dev03:162.242.195.82"
        volumes: 
            - wso2carbon:/home/wso2carbon
        ports:
            - "8280:8280"
            - "8243:8243"
            - "9443:9443"
            - "9999:9999"
            - "11111:11111"
        deploy:
            mode: replicated
            replicas: 1
            placement:
            # run application only in one server 
              constraints:
               - node.hostname == ks-dmp-dev03
            update_config:
              parallelism: 1
              delay: 10s
            resources:
                limits:
                    cpus: '2'
                    memory: 6G
                reservations:
                    cpus: '1'
                    memory: 1G
            restart_policy:
              condition: on-failure
              delay: 10s
              max_attempts: 3
volumes:
  wso2carbon:
networks:
  wso2test:
