version: '3.3'

networks:
  default:
    external:
      name: localdev

services:
  prometheus:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - /grid/0/prometheus/alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--web.external-url=http://example.com:9090/'
    ports:
      - 0.0.0.0:9093:9093
    environment:
      - no_proxy=127.0.0.0/8,10.0.0.0/8,*.example.com
      - http_proxy=http://sgproxy.example.com:3128
      - https_proxy=http://sgproxy.example.com:3128
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    restart: always